# UTS-3 My Stories for You

Aku dilahirkan di keluarga yang berpendidikan. Ayah dan Ibuku lulusan S1 universitas yang cukup ternama. Mungkin karena sifat genetik, aku memiliki kemampuan akademik yang lebih menonjol di pendidikan tingkat awal. Di tingkat sekolah dasar, aku selalu mendapat ranking di kelas. Aku merasa pelajarannya tidak sulit. Bahkan bingung ketika melihat teman sekelasku kesulitan memahami materi.

Mendekati akhir kelas 6, aku bersiap untuk mengikuti Ujian Nasional. Layaknya ujian biasa, aku bersiap dengan belajar seperti biasa. Pada hari pengerjaan, aku mengerjakan ujiannya dengan lancar. Menurutku, itu seperti ujian biasanya. Selesai minggu ujian, aku merasa yakin mendapatkan nilai yang maksimal.

Hari pengumuman pun tiba. Seluruh siswa berkumpul di lapangan dan diberikan kertas berisi nilai ujian untuk murid tertentu. Ya, pembagian dilakukan secara acak. Entah mengapa, tapi Aku tidak memedulikan itu. Aku hanya yakin Aku mendapat nilai yang bagus. Akhirnya aku mendapatkan kertas dengan namaku. Aku terkejut. Nilainya tidak sesuai yang ku harapkan. Bahkan, lebih rendah dari rata-rata. Aku bingung, apa yang salah? Aku merasa pengerjaanku lancar. Apakah persiapanku yang kurang? Apakah aku meremehkan ujian ini? Banyak pikiran terlintas di benakku, tapi satu hal yang aku tahu pasti, aku tidak tahu apa kata orang tua ku yang mengharapkan yang terbaik dari aku.

Aku merasa *down*, inikah rasanya kekalahan? Aku tidak pernah merasakan hal itu sebelumnya. Dan parahnya, mengalami kekalahan sebesar itu di salah satu momen penting yaitu Ujian Nasional? Aku terus memikirkan hal itu selama berhari-hari. Melihat ekspresi kecewa yang tersirat dari wajah orang tuaku, sungguh memalukan. Hal ini akhirnya membentuk sikap pesimistis di dalam diriku. Aku pikir, jika aku berharap yang terbaik, maka akan sakit rasanya jika gagal, seperti sakit waktu itu. Sebaliknya, jika aku berharap yang terburuk, maka tidak akan apa-apa jika aku gagal. Aku tahu ini sifat yang buruk tapi aku rasa ini merupakan jalur pelarianku.

Beberapa minggu berlalu dan akhirnya terungkap bahwa ada permainan nilai Ujian Nasional yang terjadi di daerahku oleh pihak yang di atas. Sekolahku terlibat dalam permainan tersebut yang menyebabkan turunnya semua nilai siswa di sekolah itu, termasuk aku. Walau akhirnya terungkap dan aku merasa sedikit terhibur, rasa *down* itu tetap berada didalam diriku. Aku tidak ingin merasakan hal yang sama lagi. Pada akhirnya, aku tetap mempertahankan sifatku sampai menjelang kuliah.

Memasuki jenjang perkuliahan, aku semakin menjadi dewasa. Pikiran dan emosionalku semakin matang, walau masih jauh dari kata sempurna. Di ITB, banyak orang-orang hebat disekitarku. Ada yang mempunyai kemampuan akademik jauh lebih tinggi, ada juga yang mempunyai pengalaman jauh lebih banyak dariku. Namun, aku sudah terbiasa dengan ini karena sifatku selama ini. Justru sekarang, dengan pikiran dan emosi yang lebih dewasa, aku mulai berpikir tidak ada salahnya jika kamu tidak diatas. Namun, bukan berarti kita tidak boleh berusaha untuk menjadi yang teratas. Disini, aku memperbanyak pengalamanku dengan mengikuti berbagai lomba dan kegiatan. Walau mungkin tidak juara, tapi aku mendapat banyak pengalaman dari itu. Aku bersyukur mendapat lingkungan yang suportif dan mampu mengembalikan semangat juang di dalam diriku.

Untuk siapapun yang membaca pesan ini, jika kamu sedang merasa *down*, ingatlah bahwa kehidupan terus berputar. Kita mungkin melihat dan membandingkan diri kita dengan orang lain. Namun apakah kamu yakin bahwa komparasimu itu adil? Kita tidak bisa mengetahui pasti akan hal itu. Satu-satunya hal yang bisa menjadi fokusmu adalah dirimu sendiri. Carilah pelarian yang positif. Jangan lupa juga untuk menempatkan dirimu di lingkungan yang suportif agar dirimu bisa semangat kembali!