# UTS-2 My Songs for You

{{< video https://youtu.be/zDHOW9PdQYE?si=Ha_sHI2bn24S8Vq9>}}

GAC (Gamaliél Audrey Cantika) - Bahagia

[Verse 1]

Hai hai apa kabar kawan
Siapkah kau untuk melangkahi masalahmu hadapi esok pagi
Hai hai apa kabar kawan
Siapkah kau untuk melangkah kemasa depan menantikan pelangi


[Verse 2]

Percayalah kawan esok kan berbeda
pasti kan engkau mencoba
Buat mimpimu jadi nyata oh nyata
Kita semua pasti bisa asalkan kita melangkah
Sambut hari yang indah


[Chorus]

Marilah kita mensyukuri semua berkat Tuhan hidup ini
Kita bahagia kita bahagia
Bersama hangatnya mentari nikmati dan lukiskan memori
Kita bahagia kita bahagia
Ba ha gia iya
Ba ha gia iyaiya
Ba ha gia hoyeee


[Verse 3]

Hai hai bagaimana kawan
Apakah kau merangkai semua citamu bebaskan harapanmu
Hai hai bagaimana kawan
Apakah Kau menapaki babak baru pancarkan semangatmu

[Verse 4]

Percayalah kawan esok kan berbeda
pasti kan engkau mencoba
Buat mimpimu jadi nyata oh nyata
Kita semua pasti bisa asalkan kita melangkah
Sambut hari yang indah


[Chorus]

Marilah kita mensyukuri semua berkat Tuhan hidup ini
Kita bahagia kita bahagia
Bersama hangatnya mentari nikmati dan lukiskan memori
Kita bahagia kita bahagia
Ba ha gia iya
Ba ha gia iyaiya
Ba ha gia hoyeee

Marilah kita mensyukuri nikmati dan lukiskan memori
Kita bahagia kita bahagia
Ba ha gia iya
Ba ha gia iyaiya
Ba ha gia hoyeee Jalani hidup ini
Ba ha gia iya
Ba ha gia iyaiya
Ba ha gia hoyeee Jalani hidup ini

---

Menurutku mendorong pendengar untuk tetap semangat, bersyukur atas anugerah hidup, dan menikmati setiap momen kebahagiaan karena "esok akan lebih baik jika kita terus berusaha dan melangkah maju."